workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 90
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: lernzeit_asc
    environment:
      ios_signing:
        provisioning_profiles:
          - delernzeitapp_App_Store
        certificates:
          - cert
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_STORE_APP_ID: "6789603688"
      node: 22
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build web app
        script: npm run build
      - name: Prepare and Sync iOS platform
        script: |
          npm install @capacitor/ios @capacitor/cli
          rm -rf ios
          npx cap add ios
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          # Gehe in den Ordner, in dem Capacitor das Podfile erwartet
          cd ios/App
          pod install --repo-update
      - name: Fetch signing files
        script: xcode-project use-profiles
      - name: Set iOS version
        script: |
          cd ios/App
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID") || LATEST_BUILD_NUMBER=0
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          agvtool new-version -all $NEW_BUILD_NUMBER
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
