platform :ios, '15.0'
use_frameworks!

target 'App' do
  # Capacitor Pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end

# Hook zur Vermeidung von "Multiple commands produce" Fehlern
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Verhindert doppeltes Einbetten der Frameworks
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
