// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { nativeStorageAdapter } from '@/services/nativeStorageAdapter';

const SUPABASE_URL = "https://fsmgynpdfxkaiiuguqyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzbWd5bnBkZnhrYWlpdWd1cXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTg4ODYsImV4cCI6MjA2ODI3NDg4Nn0.unk2ST0Wcsw7RJz-BGrCqQpXSgLJQpAQPgJ-ImGCv-Q";

const resolveAuthStorage = () => {
  // On native platforms, use the native storage adapter (backed by Capacitor Preferences)
  // which persists sessions across app restarts reliably
  try {
    // Dynamic check - nativeStorageAdapter works on all platforms
    // On web it writes through to its internal cache (localStorage not needed for adapter)
    // On native it uses Capacitor Preferences
    const testKey = '__supabase_storage_test__';
    window.localStorage.setItem(testKey, 'ok');
    window.localStorage.removeItem(testKey);
    // localStorage works - but on native we still prefer the native adapter
    // because WebView localStorage can be cleared by the OS
    const { Capacitor } = require('@capacitor/core');
    if (Capacitor.isNativePlatform()) {
      return nativeStorageAdapter;
    }
    return window.localStorage;
  } catch {
    // localStorage not available - use native adapter (works as in-memory fallback too)
    return nativeStorageAdapter;
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: resolveAuthStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});