// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { Capacitor } from '@capacitor/core';
import { nativeStorageAdapter } from '@/services/nativeStorageAdapter';

const SUPABASE_URL = "https://fsmgynpdfxkaiiuguqyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzbWd5bnBkZnhrYWlpdWd1cXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTg4ODYsImV4cCI6MjA2ODI3NDg4Nn0.unk2ST0Wcsw7RJz-BGrCqQpXSgLJQpAQPgJ-ImGCv-Q";

const resolveAuthStorage = () => {
  // On native platforms, always use the native storage adapter
  // (backed by Capacitor Preferences) which persists across app restarts
  // and is not subject to WebView localStorage clearing
  if (Capacitor.isNativePlatform()) {
    return nativeStorageAdapter;
  }

  // On web, prefer localStorage with in-memory fallback
  try {
    const testKey = '__supabase_storage_test__';
    window.localStorage.setItem(testKey, 'ok');
    window.localStorage.removeItem(testKey);
    return window.localStorage;
  } catch {
    console.warn('localStorage unavailable, using in-memory storage fallback');
    return nativeStorageAdapter;
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: resolveAuthStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});